-- Flight ticket cost ledger (per-person line items)
CREATE TABLE IF NOT EXISTS public.flight_cost_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id bigint NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  person_id integer NOT NULL REFERENCES public.persons(id) ON DELETE CASCADE,
  cost_type text NOT NULL,
  leg text NOT NULL DEFAULT 'both',
  amount numeric NOT NULL DEFAULT 0,
  currency text,
  paid_at date,
  vendor text,
  receipt_no text,
  note text,
  created_by uuid,
  created_by_email text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT flight_cost_items_leg_check CHECK (leg IN ('out', 'ret', 'both', 'unallocated')),
  CONSTRAINT flight_cost_items_cost_type_check CHECK (cost_type IN (
    'base_out', 'base_ret', 'package', 'baggage_prepaid', 'baggage_overage',
    'change_fee', 'cancel_fee', 'reissue', 'agency_fee', 'refund', 'other'
  ))
);

CREATE INDEX IF NOT EXISTS flight_cost_items_project_id_idx ON public.flight_cost_items(project_id);
CREATE INDEX IF NOT EXISTS flight_cost_items_person_id_idx ON public.flight_cost_items(person_id);

ALTER TABLE public.flight_cost_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY flight_cost_items_select ON public.flight_cost_items
  FOR SELECT USING (private.can_read_project(project_id));
CREATE POLICY flight_cost_items_insert ON public.flight_cost_items
  FOR INSERT WITH CHECK (private.can_edit_project(project_id));
CREATE POLICY flight_cost_items_update ON public.flight_cost_items
  FOR UPDATE USING (private.can_edit_project(project_id));
CREATE POLICY flight_cost_items_delete ON public.flight_cost_items
  FOR DELETE USING (private.can_edit_project(project_id));
